package config

const (
	//Human sprite settings
	HUMAN_WIDTH = 40.0

	//Zombie sprite settings
	ZOMBIE_WIDTH = 30.0

	BULLET_WIDTH = 10.0

	//Don't touch below this point
	HUMAN_PIC_WIDTH         = 148.0
	HUMAN_HEIGHT_WIDTH_FRAC = 228.0 / 123.0
	HUMAN_SCALE             = HUMAN_WIDTH / HUMAN_PIC_WIDTH
	HUMAN_HEIGHT            = HUMAN_WIDTH * HUMAN_HEIGHT_WIDTH_FRAC

	ZOMBIE_PIC_WIDTH         = 31.0
	ZOMBIE_HEIGHT_WIDTH_FRAC = 72.0 / 31.0
	ZOMBIE_SCALE             = ZOMBIE_WIDTH / ZOMBIE_PIC_WIDTH
	ZOMBIE_HEIGHT            = ZOMBIE_WIDTH * ZOMBIE_HEIGHT_WIDTH_FRAC

	BULLET_PIC_WIDTH         = 192.0
	BULLET_HEIGHT_WIDTH_FRAC = 511.0 / 192.0
	BULLET_SCALE             = BULLET_WIDTH / BULLET_PIC_WIDTH
	BULLET_HEIGHT            = BULLET_WIDTH * BULLET_HEIGHT_WIDTH_FRAC

	//Made to fit with shotgun/rifle
	GUNPOSX = HUMAN_WIDTH * 0.34
	GUNPOSY = HUMAN_HEIGHT * 0.5
)
